export const APIPermissionsDefinitions = {
	Sites: [
		{
			adminConsentDescription: "Allows the application to have full control of all site collections on behalf of the signed-in user.",
			adminConsentDisplayName: "Have full control of all site collections",
			type: "Admin",
			userConsentDescription: "Allow the application to have full control of all site collections on your behalf.",
			userConsentDisplayName: "Have full control of all your site collections",
			value: "Sites.FullControl.All",
		},
		{
			adminConsentDescription: "Allows the application to create or delete document libraries and lists in all site collections on behalf of the signed-in user.",
			adminConsentDisplayName: "Create, edit, and delete items and lists in all site collections",
			type: "User",
			userConsentDescription: "Allow the application to create or delete document libraries and lists in all site collections on your behalf.",
			userConsentDisplayName: "Create, edit, and delete items and lists in all your site collections",
			value: "Sites.Manage.All",
		},
		{
			adminConsentDescription: "Allows the application to read documents and list  items in all site collections on behalf of the signed-in user",
			adminConsentDisplayName: "Read items in all site collections",
			type: "User",
			userConsentDescription: "Allow the application to read documents and list items in all site collections on your behalf",
			userConsentDisplayName: "Read items in all site collections",
			value: "Sites.Read.All",
		},
		{
			adminConsentDescription: "Allows the application to edit or delete documents and list items in all site collections on behalf of the signed-in user.",
			adminConsentDisplayName: "Edit or delete items in all site collections",
			type: "User",
			userConsentDescription: "Allow the application to edit or delete documents and list items in all site collections on your behalf.",
			userConsentDisplayName: "Edit or delete items in all site collections",
			value: "Sites.ReadWrite.All",
		},
		{
			adminConsentDescription:
				"Allow the application to access a subset of site collections on behalf of the signed-in user.  The specific site collections and the permissions granted will be configured in SharePoint Online.",
			adminConsentDisplayName: "Access selected Sites, on behalf of the signed-in userUser",
			type: "User",
			userConsentDescription:
				"Allow the application to access a subset of site collections on behalf of the signed-in user.  The specific site collections and the permissions granted will be configured in SharePoint Online.",
			userConsentDisplayName: "Access selected Sites, on behalf of the signed-in user",
			value: "Sites.Selected",
		},
	],
	Files: [
		{
			adminConsentDescription: "Allows the app to read the signed-in user's files.",
			adminConsentDisplayName: "Read user files",
			type: "User",
			userConsentDescription: "Allows the app to read your files.",
			userConsentDisplayName: "Read your files",
			value: "Files.Read",
		},
		{
			adminConsentDescription: "Allows the app to read all files the signed-in user can access.",
			adminConsentDisplayName: "Read all files that user can access",
			type: "User",
			userConsentDescription: "Allows the app to read all files you can access.",
			userConsentDisplayName: "Read all files that you have access to",
			value: "Files.Read.All",
		},
		{
			adminConsentDescription: "(Preview) Allows the app to read files that the user selects. The app has access for several hours after the user selects a file.",
			adminConsentDisplayName: "Read files that the user selects (preview)",
			type: "User",
			userConsentDescription: "(Preview) Allows the app to read files that you select. After you select a file, the app has access to the file for several hours.",
			userConsentDisplayName: "Read selected files",
			value: "Files.Read.Selected",
		},
		{
			adminConsentDescription: "Allows the app to read, create, update and delete the signed-in user's files.",
			adminConsentDisplayName: "Have full access to user files",
			type: "User",
			userConsentDescription: "Allows the app to read, create, update, and delete your files.",
			userConsentDisplayName: "Have full access to your files",
			value: "Files.ReadWrite",
		},
		{
			adminConsentDescription: "Allows the app to read, create, update and delete all files the signed-in user can access.",
			adminConsentDisplayName: "Have full access to all files user can access",
			type: "User",
			userConsentDescription: "Allows the app to read, create, update and delete all files that you can access.",
			userConsentDisplayName: "Have full access to all files you have access to",
			value: "Files.ReadWrite.All",
		},
		{
			adminConsentDescription: "(Preview) Allows the app to read, create, update and delete files in the application's folder.",
			adminConsentDisplayName: "Have full access to the application's folder (preview)",
			type: "User",
			userConsentDescription: "(Preview) Allows the app to read, create, update and delete files in the application's folder.",
			userConsentDisplayName: "Have full access to the application's folder",
			value: "Files.ReadWrite.AppFolder",
		},
		{
			adminConsentDescription: "(Preview) Allows the app to read and write files that the user selects. The app has access for several hours after the user selects a file.",
			adminConsentDisplayName: "Read and write files that the user selects (preview)",
			type: "User",
			userConsentDescription: "(Preview) Allows the app to read and write files that you select. After you select a file, the app has access to the file for several hours.",
			userConsentDisplayName: "Read and write selected files",
			value: "Files.ReadWrite.Selected",
		},
		{
			adminConsentDescription:
				"Allow the application to access files explicitly permissioned to the application on behalf of the signed in user.  The specific files and the permissions granted will be configured in SharePoint Online or OneDrive.",
			adminConsentDisplayName: "Access selected Files, on behalf of the signed-in user",
			type: "Admin",
			userConsentDescription:
				"Allow the application to access files explicitly permissioned to the application on behalf of the signed in user.  The specific files and the permissions granted will be configured in SharePoint Online or OneDrive.",
			userConsentDisplayName: "Access selected Files, on behalf of the signed-in user",
			value: "Files.SelectedOperations.Selected",
		},
	],
	Calendars: [
		{
			adminConsentDescription: "Allows the app to read events in user calendars.",
			adminConsentDisplayName: "Read user calendars ",
			type: "User",
			userConsentDescription: "Allows the app to read events in your calendars.",
			userConsentDisplayName: "Read your calendars ",
			value: "Calendars.Read",
		},
		{
			adminConsentDescription: "Allows the app to read events in all calendars that the user can access, including delegate and shared calendars.",
			adminConsentDisplayName: "Read user and shared calendars",
			type: "User",
			userConsentDescription: "Allows the app to read events in all calendars that you can access, including delegate and shared calendars. ",
			userConsentDisplayName: "Read calendars you can access",
			value: "Calendars.Read.Shared",
		},
		{
			adminConsentDescription: "Allows the app to read events in user calendars, except for properties such as body, attachments, and extensions.",
			adminConsentDisplayName: "Read basic details of user calendars",
			type: "User",
			userConsentDescription: "Allows the app to read events in your calendars, except for properties such as body, attachments, and extensions.",
			userConsentDisplayName: "Read basic details of your calendars",
			value: "Calendars.ReadBasic",
		},
		{
			adminConsentDescription: "Allows the app to create, read, update, and delete events in user calendars.",
			adminConsentDisplayName: "Have full access to user calendars ",
			type: "User",
			userConsentDescription: "Allows the app to read, update, create and delete events in your calendars.",
			userConsentDisplayName: "Have full access to your calendars  ",
			value: "Calendars.ReadWrite",
		},
		{
			adminConsentDescription:
				"Allows the app to create, read, update and delete events in all calendars in the organization user has permissions to access. This includes delegate and shared calendars.",
			adminConsentDisplayName: "Read and write user and shared calendars",
			type: "User",
			userConsentDescription:
				"Allows the app to read, update, create and delete events in all calendars in your organization you have permissions to access. This includes delegate and shared calendars.",
			userConsentDisplayName: "Read and write to your and shared calendars",
			value: "Calendars.ReadWrite.Shared",
		},
	],
	Mail: [
		{
			adminConsentDescription: "Allows the app to read the signed-in user's mailbox.",
			adminConsentDisplayName: "Read user mail ",
			type: "User",
			userConsentDescription: "Allows the app to read email in your mailbox.",
			userConsentDisplayName: "Read your mail ",
			value: "Mail.Read",
		},
		{
			adminConsentDescription: "Allows the app to read mail a user can access, including their own and shared mail.",
			adminConsentDisplayName: "Read user and shared mail",
			type: "User",
			userConsentDescription: "Allows the app to read mail you can access, including shared mail.",
			userConsentDisplayName: "Read mail you can access",
			value: "Mail.Read.Shared",
		},
		{
			adminConsentDescription: "Allows the app to read email in the signed-in user's mailbox except body, previewBody, attachments and any extended properties.",
			adminConsentDisplayName: "Read user basic mail",
			type: "User",
			userConsentDescription: "Allows the app to read email in the signed-in user's mailbox except body, previewBody, attachments and any extended properties.",
			userConsentDisplayName: "Read user basic mail",
			value: "Mail.ReadBasic",
		},
		{
			adminConsentDescription:
				"Allows the app to read mail the signed-in user can access, including their own and shared mail, except for body, bodyPreview, uniqueBody, attachments, extensions, and any extended properties.",
			adminConsentDisplayName: "Read user and shared basic mail",
			type: "User",
			userConsentDescription: "Allows the app to read mail you can access, including shared mail except body, previewBody, uniqueBody, attachments, extensions, and any extended properties.",
			userConsentDisplayName: "Read basic mail you can access",
			value: "Mail.ReadBasic.Shared",
		},
		{
			adminConsentDescription: "Allows the app to create, read, update, and delete email in user mailboxes. Does not include permission to send mail.",
			adminConsentDisplayName: "Read and write access to user mail ",
			type: "User",
			userConsentDescription: "Allows the app to read, update, create and delete email in your mailbox. Does not include permission to send mail.",
			userConsentDisplayName: "Read and write access to your mail ",
			value: "Mail.ReadWrite",
		},
		{
			adminConsentDescription:
				"Allows the app to create, read, update, and delete mail a user has permission to access, including their own and shared mail. Does not include permission to send mail.",
			adminConsentDisplayName: "Read and write user and shared mail",
			type: "User",
			userConsentDescription:
				"Allows the app to read, update, create, and delete mail you have permission to access, including your own and shared mail. Does not allow the app to send mail on your behalf.",
			userConsentDisplayName: "Read and write mail you can access",
			value: "Mail.ReadWrite.Shared",
		},
	],
	User: [
		{
			adminConsentDescription:
				"Allows users to sign-in to the app, and allows the app to read the profile of signed-in users. It also allows the app to read basic company information of signed-in users.",
			adminConsentDisplayName: "Sign in and read user profile",
			type: "User",
			userConsentDescription: "Allows you to sign in to the app with your organizational account and let the app read your profile. It also allows the app to read basic company information.",
			userConsentDisplayName: "Sign you in and read your profile",
			value: "User.Read",
		},
		{
			adminConsentDescription: "Allows the app to read the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user.",
			adminConsentDisplayName: "Read all users' full profiles",
			type: "Admin",
			userConsentDescription: "Allows the app to read the full set of profile properties, reports, and managers of other users in your organization, on your behalf.",
			userConsentDisplayName: "Read all users' full profiles",
			value: "User.Read.All",
		},
		{
			adminConsentDescription:
				"Allows the app to read a basic set of profile properties of other users in your organization on behalf of the signed-in user. This includes display name, first and last name, email address and photo.",
			adminConsentDisplayName: "Read all users' basic profiles",
			type: "User",
			userConsentDescription:
				"Allows the app to read a basic set of profile properties of other users in your organization on your behalf. Includes display name, first and last name, email address and photo.",
			userConsentDisplayName: "Read all users' basic profiles",
			value: "User.ReadBasic.All",
		},
		{
			adminConsentDescription: "Allows the app to read your profile. It also allows the app to update your profile information on your behalf.",
			adminConsentDisplayName: "Read and write access to user profile",
			type: "User",
			userConsentDescription:
				"Allows the app to read your profile, and discover your group membership, reports and manager. It also allows the app to update your profile information on your behalf.",
			userConsentDisplayName: "Read and update your profile",
			value: "User.ReadWrite",
		},
		{
			adminConsentDescription: "Allows the app to read and write the full set of profile properties, reports, and managers of other users in your organization, on behalf of the signed-in user.",
			adminConsentDisplayName: "Read and write all users' full profiles",
			type: "Admin",
			userConsentDescription: "Allows the app to read and write the full set of profile properties, reports, and managers of other users in your organization, on your behalf.",
			userConsentDisplayName: "Read and write all users' full profiles",
			value: "User.ReadWrite.All",
		},
	],
};
